### ISSUE TITLE
Geneanet: gmi breaks children

### ISSUE THREAD

**Issue by raphink** [jeffg2k/SmartCopy#56]
The `s/img/gmi/ig` replacement breaks children detection. That is because `img` tags are not closed apparently, and `gmi` tags are not automatically self-closed by Chromium. As a result, ">ul >li" does not match if there are images in the marriage line (e.g. if the parents or witnesses are listed, with their gender image).

**Comment by jeffg2k** [comment]
Do you have an example link I can test new code against?  Maybe I can figure a way around it.  I rather not allow images to download as it can have a big impact on processing time if there are a lot of relationships.

**Comment by raphink** [comment]
Sure, here's an example: http://gw.geneanet.org/modestine?lang=en&p=paul+aime&n=pajon with https://www.geni.com/people/Paul-Pajon/6000000052416899869

It seems the witnesses part makes it fail. Reverting to `img` instead of `gmi` fixes the children problem, but then SmartCopy doesn't remember profiles.

**Comment by jeffg2k** [comment]
Let's give https://github.com/jeffg2k/SmartCopy/commit/cc4a5d23221a892da875808ba3c2f476f118f590 a shot.  I replaced img with track, which is another self closing tag used for the text track for video or audio - something I don't expect to see in geneanet.  This prevents the downloading of the images, but still allows it to function.  Wonder if I should do this to all the other collections, since I the gmi thing on about all of them.

**Comment by raphink** [comment]
I'm guessing the main problem is that Geneanet doesn't close the `img` tags as they should.
